export const MOVEMENT_DATA = {
    GET_ALL: 'GET_ALL'
}

export const WOD_DATA = {
    GET_ALL: 'GET_ALL'
}

export const HEARTS = {
    ADD_HEART: 'ADD_HEART',
    REMOVE_HEART: 'REMOVE_HEART'
}

export const HELPERS = {
    SET_SYNCINGDB: 'SET_SYNCINGDB',
    UPDATE_P: 'UPDATE_P'
}

export const STRENGTH = {
    SET_MOVEMENT: 'SET_MOVEMENT',
    SET_WEIGHT: 'SET_WEIGHT',
    CALCULATE_PERCENTILE: 'CALCULATE_PERCENTILE'
}

export const USER = {
    TOGGLE_DARKMODE: 'TOGGLE_DARKMODE',
    TOGGLE_GENDER: 'TOGGLE_GENDER',
    SET_BODYWEIGHT: 'SET_BODYWEIGHT',
    SET_WEIGHT_UNIT: 'SET_WEIGHT_UNIT',
    TOGGLE_WEIGHT_UNIT: 'TOGGLE_WEIGHT_UNIT',
    SET_HEIGHT_UNIT: 'SET_HEIGHT_UNIT',
    SET_DISTANCE_UNIT: 'SET_DISTANCE_UNIT',
    SET_DURATION_UNIT: 'SET_DURATION_UNIT',
    SET_FITNESS_LEVEL: 'SET_FITNESS_LEVEL',
    SET_USER: 'SET_USER',
    SET_NEWSLETTER: 'SET_NEWSLETTER',
    SET_REPHAOS: 'SET_REPHAOS',
    UPDATE_NAME: 'UPDATE_NAME'
}

export const WORKOUT = {
    SET_WORKOUT: 'SET_WORKOUT',
    SET_NAME: 'SET_NAME',
    ADD_WOD: 'ADD_WOD',
    EDIT_WOD: 'EDIT_WOD',
    OVERWRITE_WOD: 'OVERWRITE_WOD',
    REMOVE_WOD: 'REMOVE_WOD',
    SWITCH_WODS: 'SWITCH_WODS',
    ADD_MOVEMENT: 'ADD_MOVEMENT',
    EDIT_MOVEMENT: 'EDIT_MOVEMENT',
    OVERWRITE_MOVEMENT: 'OVERWRITE_MOVEMENT',
    REMOVE_MOVEMENT: 'REMOVE_MOVEMENT',
    SWITCH_MOVEMENTS: 'SWITCH_MOVEMENTS',
    SORT_MOVEMENTS: 'SORT_MOVEMENTS',
    NEW_EDITED_MOVEMENT: 'NEW_EDITED_MOVEMENT',
    SET_EDITED_MOVEMENT: 'SET_EDITED_MOVEMENT',
    SAVE_EDITED_MOVEMENT: 'SAVE_EDITED_MOVEMENT',
    RESET_EDITED_MOVEMENT: 'RESET_EDITED_MOVEMENT',
    CHANGE_MOVEMENT_TYPE: 'CHANGE_MOVEMENT_TYPE',
    NEW_EDITED_WOD: 'NEW_EDITED_WOD',
    SET_EDITED_WOD: 'SET_EDITED_WOD',
    SAVE_EDITED_WOD: 'SAVE_EDITED_WOD',
    RESET_EDITED_WOD: 'RESET_EDITED_WOD',
    ADD_RESULTS_TO_WOD: 'ADD_RESULTS_TO_WOD',
    UPDATE_SCORE: 'UPDATE_SCORE',
    UPDATE_SCORE_FOR_EMOM: 'UPDATE_SCORE_FOR_EMOM',
    UPDATE_DIFFICULTY: 'UPDATE_DIFFICULTY',
    UPDATE_NAMES: 'UPDATE_NAMES',
    UPDATE_ALL: 'UPDATE_ALL',
    SET_NEW_MOVEMENT: 'SET_NEW_MOVEMENT',
    ADD_KEY_TO_MOVEMENT: 'ADD_KEY_TO_MOVEMENT',
    RESET_STATE: 'RESET_STATE',
    SET_SAVING: 'SET_SAVING',
    LOAD_WORKOUT: 'LOAD_WORKOUT',
    UPDATE_RESULTS: 'UPDATE_RESULTS',
    IMPORT: 'IMPORT',
}
